name: Publish Container Image

on:
  #workflow_run:
  #workflows: [ "GitHub Release" ]
  #branches: [ main ]
  #types: [ completed ]
  pull_request:
    branches:
      - master

env:
  NPM_TOKEN_GITHUB: ${{ secrets.NPM_TOKEN_GITHUB }}

jobs:
  create_tag:
    name: create tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.nexttag.outputs.tag}}
    steps:
      - uses: actions/checkout@v2
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1 # Opt
      - name: Generate Next Tag
        id: nexttag
        run: echo "::set-output name=tag::$((${{steps.previoustag.outputs.tag}} + 1))"
      - name: Generate Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: ${{steps.nexttag.outputs.tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_container_image:
    name: run image build for Production
    runs-on: ubuntu-latest
    needs: create_tag
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: Extract branch name
        shell: bash
        run: |
          STEP1=$GITHUB_REF
          STEP2=${STEP1#refs/}
          STEP3=${STEP2#heads/}
          STEP4=${STEP3//\//-}
          echo $STEP4
          echo "##[set-output name=branch;]$(echo ${STEP4})"
          echo "TESTING----- ${GITHUB_REF##*/}"
          echo "${{ steps.previoustag.outputs.tag }}"
          echo "${{ needs.create_tag.outputs.tag }}"
        id: extract_branch
